### ISSUE TITLE
Replace xctest in Travis CI build script with xcodebuild and xcpretty

### ISSUE THREAD

**Issue by mhadam** [snowplow/iglu-objc-client#9]
Seems to be related to this issue: https://github.com/facebook/xctool/issues/704
We can use `xcodebuild test` alone although `xc-pretty` with `xc-pretty-travis-formatter` seems to replace the formatting you get from `xctool`.

**Comment by alexanderdean** [comment]
Can we rename this ticket/commit to clarify what we replaced it *with*?
